version: '2'



services:
  postgres:
    hostname: postgres  
    image: postgres:latest
    container_name: postgres
    environment:
      - "TZ=America/Sao_Paulo"
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "5432:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
  socialApp:
    depends_on:
      - postgres
    image: cesar/social-app-cesar-vigil
    ports:
      - '8080:8080'
      

